version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK-DEFINITION-ARN>
        LoadBalancerInfo:
          ContainerName: <YOUR-CONTAINER-NAME>
          ContainerPort: <YOUR-CONTAINER-PORT>