server:
  port: 8080
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: awsome-books
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "" # When using Config Service, add "optional:configserver:"
  cloud:
    config:
      enabled: false # When using Config Service, set to true
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: true # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  # profiles:
  #   active: devz
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: rds!db-7eb08ca8-ebed-4f87-96cd-33ac95b908fa
    url: jdbc-secretsmanager:postgresql://awsome-books-db-server.cliq64c00zrx.us-east-1.rds.amazonaws.com:5432/awsome_books
    # driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    # username: <AWS-SECRECTS-MANAGER-NAME>
    # url: jdbc-secretsmanager:postgresql://<AWS-RDS-DB-URL>:5432/awsome_books
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop


polar:
  greeting: Welcome to the prod book catalog!
